ALTER TABLE tenants ADD COLUMN IF NOT EXISTS monthly_rent INTEGER;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS security_deposit INTEGER;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS lease_start DATE;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS lease_end DATE;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS bed_number VARCHAR(10);
